
import { InboxItem, SourceType } from './types';

export const MOCK_INBOX: InboxItem[] = [
  // Urgent Items (First Focus)
  {
    id: 'e-1',
    source: SourceType.EMAIL,
    sender: 'ceo@company.com',
    subject: 'URGENT: Board Deck Required ASAP',
    content: 'I need the final slides by 2 PM. This is top priority.',
    timestamp: '2023-10-27T09:05:00Z',
    read: false,
  },
  {
    id: 's-1',
    source: SourceType.SLACK,
    sender: 'Dave (DevOps)',
    subject: 'Production Outage',
    content: 'Payment gateway is throwing 500s. Customers cannot checkout. Need help.',
    timestamp: '2023-10-27T09:15:00Z',
    read: false,
  },
  {
    id: 's-99',
    source: SourceType.SLACK,
    sender: 'Automated Bot',
    subject: 'Deployment Alert',
    content: 'Pipeline #420 failed during integration tests. Rollback initiated.',
    timestamp: '2023-10-27T09:20:00Z',
    read: false,
  },
  {
    id: 'j-2',
    source: SourceType.JIRA,
    sender: 'QA Team',
    subject: 'BUG-902: Critical Login Failure',
    content: 'Users on iOS cannot log in. Blocker for release.',
    timestamp: '2023-10-27T08:30:00Z',
    read: false,
  },

  // Important Items (Second Focus)
  {
    id: 'e-3',
    source: SourceType.EMAIL,
    sender: 'client-VIP@enterprise.com',
    subject: 'Contract Renewal Questions',
    content: 'Can we review the SLA terms before signing next week?',
    timestamp: '2023-10-27T09:45:00Z',
    read: false,
  },
  {
    id: 'c-1',
    source: SourceType.CALENDAR,
    sender: 'HR',
    subject: 'Team Performance Reviews',
    content: 'Please submit your peer reviews by Friday.',
    timestamp: '2023-10-27T09:00:00Z',
    read: false,
  },
  {
    id: 's-4',
    source: SourceType.SLACK,
    sender: 'Product Manager',
    subject: 'Q4 Roadmap Review',
    content: 'Need your input on the technical feasibility of feature X.',
    timestamp: '2023-10-27T10:00:00Z',
    read: true,
  },
  {
    id: 'j-5',
    source: SourceType.JIRA,
    sender: 'Product Owner',
    subject: 'STORY-551: Mobile Dark Mode',
    content: 'Implement dark mode theming for the React Native app. High priority for Q4.',
    timestamp: '2023-10-27T11:30:00Z',
    read: false,
  },

  // Routine Items (Third Focus)
  {
    id: 'j-1',
    source: SourceType.JIRA,
    sender: 'Project Manager',
    subject: 'TICKET-4201: Update Footer',
    content: 'Update copyright year in the footer. Low priority.',
    timestamp: '2023-10-26T16:00:00Z',
    read: true,
  },
  {
    id: 'j-6',
    source: SourceType.JIRA,
    sender: 'Design Team',
    subject: 'TASK-102: Icon Export',
    content: 'Export all SVG icons for the new marketing landing page.',
    timestamp: '2023-10-26T14:00:00Z',
    read: true,
  },
  {
    id: 'e-2',
    source: SourceType.EMAIL,
    sender: 'newsletter@techweekly.com',
    subject: 'This week in AI',
    content: 'Top stories: Gemini 2.5 released, new coding frameworks...',
    timestamp: '2023-10-27T08:00:00Z',
    read: false,
  },
  {
    id: 's-2',
    source: SourceType.SLACK,
    sender: 'Emily (Marketing)',
    subject: 'Lunch Plans',
    content: 'Tacos at 12:30?',
    timestamp: '2023-10-27T10:30:00Z',
    read: false,
  },
  {
    id: 's-3',
    source: SourceType.SLACK,
    sender: 'General Channel',
    subject: 'Happy Birthday!',
    content: 'Cake in the breakroom.',
    timestamp: '2023-10-27T11:00:00Z',
    read: false,
  },
  {
    id: 's-10',
    source: SourceType.SLACK,
    sender: 'Random',
    subject: 'Coffee Run?',
    content: 'Anyone want to grab a coffee downstairs in 5 mins?',
    timestamp: '2023-10-27T14:00:00Z',
    read: false,
  },
   {
    id: 'e-4',
    source: SourceType.EMAIL,
    sender: 'legal@company.com',
    subject: 'Compliance Training',
    content: 'Reminder: Annual training due in 14 days.',
    timestamp: '2023-10-27T07:00:00Z',
    read: false,
  }
];
